### ISSUE TITLE
ceph rgw整keystone設定

### ISSUE THREAD

**Issue by hrchu** [kairen/openstack-ubuntu#6]
https://github.com/kairen/openstack-ubuntu/blob/master/ubuntu-binary/keystone/ceph-keystone.md

1. 一般不需要設定nss
2. 新版建議用keystone v3 認證
例子 http://zhengtianbao.com/ceph/radosgw/2016/05/31/ceph-radosgw-install.html

**Comment by kairen** [comment]
Okay, thanks for your reply!

**Comment by kairen** [comment]
Fix by https://github.com/kairen/openstack-ubuntu/commit/d97e0a6e500bda78d19ae5f37879305e8fcac283
